#number of threads
threads=40
#http port number
httpport=8080
#https port number
httpsport=8081
#ipv4 bind address
bindipv4=127.0.0.1
#ipv6 bind address
bindipv6=::1
#debug level : 1-5
debuglevel=1
#transport mechanism : secure / non-secure / both
transport=both
#session cookie name
session=SID
#max age
maxage=3600
