//Copyright Anoop Kumar Narayanan - 2025 //httpdwin
#include <iostream>
#include <map>

using namespace std;


std::map<string,string> httpHeaders =
{
    {"Accept", "0" },
    {"Accept-CH", "1" },
    {"Accept-Encoding", "2" },
    {"Accept-Language", "3" },
    {"Accept-Patch", "4" },
    {"Accept-Post", "5" },
    {"Accept-Ranges", "6" },
    {"Access-Control-Allow-Credentials", "7" },
    {"Access-Control-Allow-Headers", "8" },
    {"Access-Control-Allow-Methods", "9" },
    {"Access-Control-Allow-Origin", "10" },
    {"Access-Control-Expose-Headers", "11" },
    {"Access-Control-Max-Age", "12" },
    {"Access-Control-Request-Headers", "13" },
    {"Access-Control-Request-Method", "14" },
    {"Age", "15" },
    {"Allow", "16" },
    {"Alt-Svc", "17" },
    {"Alt-Used", "18" },
    {"Attribution-Reporting-EligibleExperimental", "19" },
    {"Attribution-Reporting-Register-SourceExperimental", "20" },
    {"Attribution-Reporting-Register-TriggerExperimental", "21" },
    {"Authorization", "22" },
    {"Available-DictionaryExperimental", "23" },
    {"Cache-Control", "24" },
    {"Clear-Site-Data", "25" },
    {"Connection", "26" },
    {"Content-Digest", "27" },
    {"Content-Disposition", "28" },
    {"Content-DPRNon-standardDeprecated", "29" },
    {"Content-Encoding", "30" },
    {"Content-Language", "31" },
    {"Content-Length", "32" },
    {"Content-Location", "33" },
    {"Content-Range", "34" },
    {"Content-Security-Policy", "35" },
    {"Content-Security-Policy-Report-Only", "36" },
    {"Content-Type", "37" },
    {"Cookie", "38" },
    {"Critical-CHExperimental", "39" },
    {"Cross-Origin-Embedder-Policy", "40" },
    {"Cross-Origin-Opener-Policy", "41" },
    {"Cross-Origin-Resource-Policy", "42" },
    {"Date", "43" },
    {"Device-Memory", "44" },
    {"Dictionary-IDExperimental", "45" },
    {"DNTNon-standardDeprecated", "46" },
    {"DownlinkExperimental", "47" },
    {"DPRNon-standardDeprecated", "48" },
    {"Early-DataExperimental", "49" },
    {"ECTExperimental", "50" },
    {"ETag", "51" },
    {"Expect", "52" },
    {"Expect-CTDeprecated", "53" },
    {"Expires", "54" },
    {"Forwarded", "55" },
    {"From", "56" },
    {"Host", "57" },
    {"If-Match", "58" },
    {"If-Modified-Since", "59" },
    {"If-None-Match", "60" },
    {"If-Range", "61" },
    {"If-Unmodified-Since", "62" },
    {"Keep-Alive", "63" },
    {"Last-Modified", "64" },
    {"Link", "65" },
    {"Location", "66" },
    {"Max-Forwards", "67" },
    {"NELExperimental", "68" },
    {"No-Vary-SearchExperimental", "69" },
    {"Observe-Browsing-TopicsExperimentalNon-standard", "70" },
    {"Origin", "71" },
    {"Origin-Agent-Cluster", "72" },
    {"Permissions-PolicyExperimental", "73" },
    {"PragmaDeprecated", "74" },
    {"Prefer", "75" },
    {"Preference-Applied", "76" },
    {"Priority", "77" },
    {"Proxy-Authenticate", "78" },
    {"Proxy-Authorization", "79" },
    {"Range", "80" },
    {"Referer", "81" },
    {"Referrer-Policy", "82" },
    {"Refresh", "83" },
    {"Report-ToNon-standardDeprecated", "84" },
    {"Reporting-Endpoints", "85" },
    {"Repr-Digest", "86" },
    {"Retry-After", "87" },
    {"RTTExperimental", "88" },
    {"Save-DataExperimental", "89" },
    {"Sec-CH-Prefers-Color-SchemeExperimental", "90" },
    {"Sec-CH-Prefers-Reduced-MotionExperimental", "91" },
    {"Sec-CH-Prefers-Reduced-TransparencyExperimental", "92" },
    {"Sec-CH-UAExperimental", "93" },
    {"Sec-CH-UA-ArchExperimental", "94" },
    {"Sec-CH-UA-BitnessExperimental", "95" },
    {"Sec-CH-UA-Form-FactorsExperimental", "96" },
    {"Sec-CH-UA-Full-VersionDeprecated", "97" },
    {"Sec-CH-UA-Full-Version-ListExperimental", "98" },
    {"Sec-CH-UA-MobileExperimental", "99" },
    {"Sec-CH-UA-ModelExperimental", "100" },
    {"Sec-CH-UA-PlatformExperimental", "101" },
    {"Sec-CH-UA-Platform-VersionExperimental", "102" },
    {"Sec-CH-UA-WoW64Experimental", "103" },
    {"Sec-Fetch-Dest", "104" },
    {"Sec-Fetch-Mode", "105" },
    {"Sec-Fetch-Site", "106" },
    {"Sec-Fetch-User", "107" },
    {"Sec-GPCExperimental", "108" },
    {"Sec-Purpose", "109" },
    {"Sec-Speculation-TagsExperimental", "110" },
    {"Sec-WebSocket-Accept", "111" },
    {"Sec-WebSocket-Extensions", "112" },
    {"Sec-WebSocket-Key", "113" },
    {"Sec-WebSocket-Protocol", "114" },
    {"Sec-WebSocket-Version", "115" },
    {"Server", "116" },
    {"Server-Timing", "117" },
    {"Service-Worker", "118" },
    {"Service-Worker-Allowed", "119" },
    {"Service-Worker-Navigation-Preload", "120" },
    {"Set-Cookie", "121" },
    {"Set-Login", "122" },
    {"SourceMap", "123" },
    {"Speculation-RulesExperimental", "124" },
    {"Strict-Transport-Security", "125" },
    {"Supports-Loading-ModeExperimental", "126" },
    {"TE", "127" },
    {"Timing-Allow-Origin", "128" },
    {"TkNon-standardDeprecated", "129" },
    {"Trailer", "130" },
    {"Transfer-Encoding", "131" },
    {"Upgrade", "132" },
    {"Upgrade-Insecure-Requests", "133" },
    {"Use-As-DictionaryExperimental", "134" },
    {"User-Agent", "135" },
    {"Vary", "136" },
    {"Via", "137" },
    {"Viewport-WidthNon-standardDeprecated", "138" },
    {"Want-Content-Digest", "139" },
    {"Want-Repr-Digest", "140" },
    {"WarningDeprecated", "141" },
    {"WidthNon-standardDeprecated", "142" },
    {"WWW-Authenticate", "143" },
    {"X-Content-Type-Options", "144" },
    {"X-DNS-Prefetch-ControlNon-standard", "145" },
    {"X-Forwarded-ForNon-standard", "146" },
    {"X-Forwarded-HostNon-standard", "147" },
    {"X-Forwarded-ProtoNon-standard", "148" },
    {"X-Frame-Options", "149" },
    {"X-Permitted-Cross-Domain-PoliciesNon-standard", "150" },
    {"X-Powered-ByNon-standard", "151" },
    {"X-Robots-TagNon-standard", "152" },
    {"X-XSS-ProtectionNon-standardDeprecated", "153" }
};

std::map<string,string> httpMethods =
{
    {"GET",  "0"},
    {"POST", "1"},
    {"HEAD", "2"},
    {"PUT",  "3"}
};

std::map<string,string> httpVersions = {
    {"HTTP/1.0", "0"},
    {"HTTP/1.1", "1"},
    {"HTTP/2.0", "2"}
};
