//Copyright Anoop Kumar Narayanan - 2025 //httpdwin
#include <iostream>
#include <map>

using namespace std;


std::map<string,string> httpHeaders =
{
    {"Accept", "1" },
    {"Accept-CH", "1" },
    {"Accept-Encoding", "1" },
    {"Accept-Language", "1" },
    {"Accept-Patch", "1" },
    {"Accept-Post", "1" },
    {"Accept-Ranges", "1" },
    {"Access-Control-Allow-Credentials", "1" },
    {"Access-Control-Allow-Headers", "1" },
    {"Access-Control-Allow-Methods", "1" },
    {"Access-Control-Allow-Origin", "1" },
    {"Access-Control-Expose-Headers", "1" },
    {"Access-Control-Max-Age", "1" },
    {"Access-Control-Request-Headers", "1" },
    {"Access-Control-Request-Method", "1" },
    {"Age", "1" },
    {"Allow", "1" },
    {"Alt-Svc", "1" },
    {"Alt-Used", "1" },
    {"Attribution-Reporting-EligibleExperimental", "1" },
    {"Attribution-Reporting-Register-SourceExperimental", "1" },
    {"Attribution-Reporting-Register-TriggerExperimental", "1" },
    {"Authorization", "1" },
    {"Available-DictionaryExperimental", "1" },
    {"Cache-Control", "1" },
    {"Clear-Site-Data", "1" },
    {"Connection", "1" },
    {"Content-Digest", "1" },
    {"Content-Disposition", "1" },
    {"Content-DPRNon-standardDeprecated", "1" },
    {"Content-Encoding", "1" },
    {"Content-Language", "1" },
    {"Content-Length", "1" },
    {"Content-Location", "1" },
    {"Content-Range", "1" },
    {"Content-Security-Policy", "1" },
    {"Content-Security-Policy-Report-Only", "1" },
    {"Content-Type", "1" },
    {"Cookie", "1" },
    {"Critical-CHExperimental", "1" },
    {"Cross-Origin-Embedder-Policy", "1" },
    {"Cross-Origin-Opener-Policy", "1" },
    {"Cross-Origin-Resource-Policy", "1" },
    {"Date", "1" },
    {"Device-Memory", "1" },
    {"Dictionary-IDExperimental", "1" },
    {"DNTNon-standardDeprecated", "1" },
    {"DownlinkExperimental", "1" },
    {"DPRNon-standardDeprecated", "1" },
    {"Early-DataExperimental", "1" },
    {"ECTExperimental", "1" },
    {"ETag", "1" },
    {"Expect", "1" },
    {"Expect-CTDeprecated", "1" },
    {"Expires", "1" },
    {"Forwarded", "1" },
    {"From", "1" },
    {"Host", "1" },
    {"If-Match", "1" },
    {"If-Modified-Since", "1" },
    {"If-None-Match", "1" },
    {"If-Range", "1" },
    {"If-Unmodified-Since", "1" },
    {"Keep-Alive", "1" },
    {"Last-Modified", "1" },
    {"Link", "1" },
    {"Location", "1" },
    {"Max-Forwards", "1" },
    {"NELExperimental", "1" },
    {"No-Vary-SearchExperimental", "1" },
    {"Observe-Browsing-TopicsExperimentalNon-standard", "1" },
    {"Origin", "1" },
    {"Origin-Agent-Cluster", "1" },
    {"Permissions-PolicyExperimental", "1" },
    {"PragmaDeprecated", "1" },
    {"Prefer", "1" },
    {"Preference-Applied", "1" },
    {"Priority", "1" },
    {"Proxy-Authenticate", "1" },
    {"Proxy-Authorization", "1" },
    {"Range", "1" },
    {"Referer", "1" },
    {"Referrer-Policy", "1" },
    {"Refresh", "1" },
    {"Report-ToNon-standardDeprecated", "1" },
    {"Reporting-Endpoints", "1" },
    {"Repr-Digest", "1" },
    {"Retry-After", "1" },
    {"RTTExperimental", "1" },
    {"Save-DataExperimental", "1" },
    {"Sec-Browsing-TopicsExperimentalNon-standard", "1" },
    {"Sec-CH-Prefers-Color-SchemeExperimental", "1" },
    {"Sec-CH-Prefers-Reduced-MotionExperimental", "1" },
    {"Sec-CH-Prefers-Reduced-TransparencyExperimental", "1" },
    {"Sec-CH-UAExperimental", "1" },
    {"Sec-CH-UA-ArchExperimental", "1" },
    {"Sec-CH-UA-BitnessExperimental", "1" },
    {"Sec-CH-UA-Form-FactorsExperimental", "1" },
    {"Sec-CH-UA-Full-VersionDeprecated", "1" },
    {"Sec-CH-UA-Full-Version-ListExperimental", "1" },
    {"Sec-CH-UA-MobileExperimental", "1" },
    {"Sec-CH-UA-ModelExperimental", "1" },
    {"Sec-CH-UA-PlatformExperimental", "1" },
    {"Sec-CH-UA-Platform-VersionExperimental", "1" },
    {"Sec-CH-UA-WoW64Experimental", "1" },
    {"Sec-Fetch-Dest", "1" },
    {"Sec-Fetch-Mode", "1" },
    {"Sec-Fetch-Site", "1" },
    {"Sec-Fetch-User", "1" },
    {"Sec-GPCExperimental", "1" },
    {"Sec-Purpose", "1" },
    {"Sec-Speculation-TagsExperimental", "1" },
    {"Sec-WebSocket-Accept", "1" },
    {"Sec-WebSocket-Extensions", "1" },
    {"Sec-WebSocket-Key", "1" },
    {"Sec-WebSocket-Protocol", "1" },
    {"Sec-WebSocket-Version", "1" },
    {"Server", "1" },
    {"Server-Timing", "1" },
    {"Service-Worker", "1" },
    {"Service-Worker-Allowed", "1" },
    {"Service-Worker-Navigation-Preload", "1" },
    {"Set-Cookie", "1" },
    {"Set-Login", "1" },
    {"SourceMap", "1" },
    {"Speculation-RulesExperimental", "1" },
    {"Strict-Transport-Security", "1" },
    {"Supports-Loading-ModeExperimental", "1" },
    {"TE", "1" },
    {"Timing-Allow-Origin", "1" },
    {"TkNon-standardDeprecated", "1" },
    {"Trailer", "1" },
    {"Transfer-Encoding", "1" },
    {"Upgrade", "1" },
    {"Upgrade-Insecure-Requests", "1" },
    {"Use-As-DictionaryExperimental", "1" },
    {"User-Agent", "1" },
    {"Vary", "1" },
    {"Via", "1" },
    {"Viewport-WidthNon-standardDeprecated", "1" },
    {"Want-Content-Digest", "1" },
    {"Want-Repr-Digest", "1" },
    {"WarningDeprecated", "1" },
    {"WidthNon-standardDeprecated", "1" },
    {"WWW-Authenticate", "1" },
    {"X-Content-Type-Options", "1" },
    {"X-DNS-Prefetch-ControlNon-standard", "1" },
    {"X-Forwarded-ForNon-standard", "1" },
    {"X-Forwarded-HostNon-standard", "1" },
    {"X-Forwarded-ProtoNon-standard", "1" },
    {"X-Frame-Options", "1" },
    {"X-Permitted-Cross-Domain-PoliciesNon-standard", "1" },
    {"X-Powered-ByNon-standard", "1" },
    {"X-Robots-TagNon-standard", "1" },
    {"X-XSS-ProtectionNon-standardDeprecated", "1" }
};

std::map<string,string> httpMethods =
{
    {"GET",  "1"},
    {"POST", "1"},
    {"HEAD", "1"},
    {"PUT",  "1"}
};

std::map<string,string> httpVersions = {
    {"HTTP/1.0", "1"},
    {"HTTP/1.1", "1"},
    {"HTTP/2.0", "1"}
};
