
CC=gcc
CPP=g++
LIBS=-lssl -lcrypto -L/usr/lib64/ -ldl  -lm
INC=-I./ -fno-strict-overflow -Wsign-compare -fexceptions -mbranch-protection=standard   -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -mbranch-protection=standard
python_version:=$(shell bash -c 'read -p "Enter Python Version:" python_version; echo $$python_version;')
LIBS:=$(LIBS) -lpython$(python_version)
INC:=$(INC) -I/usr/include/python$(python_version)

#Linux should be able to use mac tahoe flag
#If anything additional is required for linux, a new macro -DFOR_LILNUX will be added.
FLAGS=-DMAC_TAHOE -Wall -std=c++17 
OBJS=cookie.o httpdlog.o httprequest.o httpconnection.o httpheaders.o httpresponse.o threadpool.o main.o

all:HttpdWin

cookie.o:cookie.cpp
	$(CPP) cookie.cpp -c -o cookie.o $(INC) $(FLAGS) 
	
httpdlog.o:httpdlog.cpp
	$(CPP) httpdlog.cpp -c -o httpdlog.o $(INC) $(FLAGS) 
	
httprequest.o:httprequest.cpp
	$(CPP) httprequest.cpp -c -o httprequest.o $(INC) $(FLAGS) 

httpconnection.o:httpconnection.cpp 
	$(CPP) httpconnection.cpp -c -o httpconnection.o $(INC) $(FLAGS) 
	
httpheaders.o:httpheaders.cpp
	$(CPP) httpheaders.cpp -c -o httpheaders.o $(INC) $(FLAGS) 
	
httpresponse.o:httpresponse.cpp 
	$(CPP) httpresponse.cpp -c -o httpresponse.o $(INC) $(FLAGS) 

threadpool.o:threadpool.cpp
	$(CPP) threadpool.cpp -c -o threadpool.o $(INC) $(FLAGS) 
	
main.o:main.cpp
	$(CPP) main.cpp -c -o main.o $(INC) $(FLAGS) 

HttpdWin:$(OBJS)
	$(CPP) $(OBJS) -o HttpdWinLinux $(LIBS) 

clean:
	rm -f *.o core.* HttpdWinLinux
